FROM golang:1.17-alpine3.15
WORKDIR /app
COPY . .
# RUN go build -ldflags '-w -s -extldflags "-static"' -a -o application main.go
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-w -s -extldflags "-static"' -a -o application main.go