# Stage 0
# golang:1.17-alpine3.15 image contains all the tools to compile the code and prepare the native binary.

# base image for stage 0
FROM golang:1.17-alpine3.15
# current working dir
WORKDIR /app
# copy content to working dir
COPY . .
# build native binary
RUN go build -o application main.go


# Stage 1
# alpine:latest is the bare minimum image where we copy the binary file created in the earlier stage.
# earlier stage is referenced in the final stage by providing the flag --from=0.

# runtime image
FROM alpine:latest
# workdir in the runtime image
WORKDIR /app
# copy contents from stage 0
COPY --from=0 /app ./
# run the native binary
CMD ["./application"]