# base image - stage 0
FROM golang:1.17-alpine3.15
WORKDIR /app
COPY . .
# RUN go build -o application main.go
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-w -s -extldflags "-static"' -a -o application main.go

# runtime image
# https://hub.docker.com/_/scratch
# explicitly empty image, this image is most useful in the context of building base images or
# super minimal images (that contain only a single binary and whatever it requires)
FROM scratch
# workdir in the runtime image
WORKDIR /app
# copy contents from stage 0
COPY --from=0 /app ./
CMD ["./application"]