# small footprint and advanced security features make Alpine Linux a perfect choice for containers such as Docker
# golang:1.17-alpine3.15 image contains all the tools to compile the code and prepare the native binary.
FROM golang:1.17-alpine3.15
# working directory inside docker
WORKDIR /app
# copy content to working dir
COPY . .
# create the native binary
RUN go build -o application main.go
# run the native binary
CMD [ "/app/application" ]